# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Github Actions

on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:
    branches:
      - 'master'
      - 'develop'

jobs:
  checks:
    name: "Gradle check + Code coverage"
    runs-on: ubuntu-latest
    steps:
      - name: setup_jdk
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: checkout
        uses: actions/checkout@v3
      - name: validation
        uses: gradle/wrapper-validation-action@v1
      - name: check
        run: ./gradlew clean check --no-daemon
      - name: code_coverage
        run: ./gradlew jacocoTestReport
      - name: codecove_integration
        uses: codecov/codecov-action@v2
        with:
          verbose: true
