# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Github Actions

on:
  push:
    branches:
      - 'master'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'master'

jobs:
  checks:
    name: "Gradle Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17']
    steps:
      - name: setup_jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: checkout
        uses: actions/checkout@v3
      - name: validation
        uses: gradle/wrapper-validation-action@v1
      - name: code quality check
        if: vars.CODE_QUALITY_CHECK_ENFORCE == 'true'
        run: ./gradlew clean codeNarcMain --no-daemon
      - name: check
        run: ./gradlew clean check -x codeNarcMain --no-daemon
  code_coverage:
    name: "Gradle Check + Code coverage"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: setup_jdk
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: checkout
        uses: actions/checkout@v3
      - name: validation
        uses: gradle/wrapper-validation-action@v1
      - name: code_coverage
        run: ./gradlew clean codeCoverageTest jacocoCodeCoverageTestReport
      - name: codecov_integration
        uses: codecov/codecov-action@v2
        with:
          verbose: true
